FROM apache/airflow:2.10.2

ARG AIRFLOW_VERSION=2.10.2
ARG PYTHON_VERSION=3.12

USER airflow

RUN pip install --no-cache-dir \
    --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-${AIRFLOW_VERSION}/constraints-${PYTHON_VERSION}.txt" \
    apache-airflow-providers-amazon \
    apache-airflow-providers-postgres \
    Faker \
    psycopg2-binary
